### ISSUE TITLE
Weird indentation for empty tuples

### ISSUE THREAD

**Issue by hochata** [wkirschbaum/elixir-ts-mode#11]
When typing a tuple in multiples lines, the indentation initially looks like this
```elixir
  {
|
  }
```
But if you start typing anything, it gets properly indented
```elixir
  {
    e|
  }
```

For contrast, inside both list and maps you get the second example indentation without the need to type anything.

**Comment by wkirschbaum** [comment]
thanks for logging this @hochata. i will have a look at this later today.

**Comment by wkirschbaum** [comment]
@hochata  This issue should be fixed for most of the scenarios. I had to regress on other indentation issues, but think they were more of an edge case and this is more important. Please let me know if the latest change fixes your issue.

**Comment by hochata** [comment]
Hi, sorry for the late response.

It is still present on the main branch, and I also noticed it happens with parenthesis.

For example, a function call with no arguments gets indented like this

```elixir
  func(
|
  )
```
But if you start typing some arguments it gets correctly fixed
```elixir
  func(
    arg|
  )
```

But I think it is a pretty minor bug. It doesn't affect usability that much, it is just annoying.

**Comment by wkirschbaum** [comment]
@hochata i will continue to tweak, but there are some limitations from the elixir tree sitter grammar where we don't always know the parent of the function, so it looks at the source node ( main node ). 

It is strange that you still get it for tuples though. Will have a further look. 

Lets leave this open.

**Comment by hochata** [comment]
My bad @wkirschbaum , I think I was running an older versions without noticing it.

As you pointed out, this is solved for tuples in main!

Should I keep this open for the function calls case? Or maybe tag it as `treesit-grammar-limitation` and close it?

**Comment by hochata** [comment]
Thinking about it, even if an issue regarding the tree-sitter grammar limitation stays open, it should be a new dedicated issue.

Thanks for solving this!
