### ISSUE TITLE
Error while calling indent-region

### ISSUE THREAD

**Issue by andreyorst** [wkirschbaum/elixir-ts-mode#12]
Hi! Thanks for the package!

I have a problem that the following code produces an error when I hit <kbd>Tab</kbd> inside the `fwrite` arglist before the `"Val:` string or before `%{`, or when selecting the whole definition and calling `indent-region`:

```elixir
  defp print_res(stats) do
    %{key: key, val: val} = stats

    :io.fwrite(
      "Key:   ~w~n" <> 
      "Val:   ~w micros~n",
      [key, val])
  end
```

The error is:

    indent--funcall-widened: Wrong type argument: number-or-marker-p, (lambda (node parent _) (cond ((equal (treesit-node-type parent) "do_block") 2) ((equal (treesit-node-type parent) "binary_operator") 2) (t 0)))

elixir-ts-mode revision: 2afb364
elixir grammar revision: `b20eaa75565243c50be5e35e253d8beb58f45d56`
heex grammar revision: `2e1348c3cf2c9323e87c2744796cf3f3868aa82a`

grammars were installed using `treesit-install-language-grammar`

**Comment by wkirschbaum** [comment]
@andreyorst  thanks for logging the issue. this issue should be solved if you update your emacs version to the latest emacs-29. The ability to set a function was only added later in emacs commit c78e19d99c0.

**Comment by andreyorst** [comment]
Thank you. I was on Emacs 30, but updating fixed the issue indeed!
