### ISSUE TITLE
With electric-pair-mode enabled there is a jumping behavior

### ISSUE THREAD

**Issue by djgoku** [wkirschbaum/elixir-ts-mode#15]
Using `electric-pair-mode` with `elixir-ts-mode` and `heex-ts-mode` there is an observed jumping if a tag isn't closed, but you insert a double quote.

emac config:
```
(electric-pair-mode t)
(setq treesit-extra-load-path '("/Users/dj_goku/dev/github/casouri/tree-sitter-module/dist"))

(use-package heex-ts-mode
  ;; :straight t
  )

(use-package elixir-ts-mode
  ;; :straight t
  :config (global-subword-mode t))

(use-package eglot
  ;; :straight t
  :config
  (dolist (mode '(elixir-ts-mode heex-ts-mode))
    (add-to-list 'eglot-server-programs `(,mode . ("/Users/dj_goku/dev/github/elixir-lsp/elixir-ls/release/language_server.sh"))))
  (add-hook 'elixir-ts-mode-hook 'eglot-ensure)
  (add-hook 'heex-ts-mode-hook 'eglot-ensure)
  (add-hook 'elixir-ts-mode-hook (lambda () (add-hook 'before-save-hook 'eglot-format-buffer nil t))))
```

example.ex:
```
def render(assigns) do
  ~H"""
    <.form phx-submit=<---- when you insert a double quote here you will jump down to the end at the triple quote
  """
end
```

**Comment by wkirschbaum** [comment]
Thanks for logging. I can reproduce this issue and will have a look.

**Comment by wkirschbaum** [comment]
@djgoku i see this is the same behavior for other languages including elixir-mode. I will tinker a bit, but if the next char is a ", when you type " it will jump. This seems to be an electric-pair-mode issue. If you can confirm this is specific to elixir-ts-mode we can leave it open, but otherwise feel i need to close this issue.

**Comment by wkirschbaum** [comment]
This seems to be a solution: https://github.com/wkirschbaum/elixir-ts-mode/pull/16

**Comment by wkirschbaum** [comment]
This should fix your issue: https://github.com/wkirschbaum/elixir-ts-mode/commit/a1121807e495b467c79f2113deacadd88553b5ef

**Comment by djgoku** [comment]
Thank you again @wkirschbaum !!
