### ISSUE TITLE
feature request: automatically add a `end` when a `do` is entered

### ISSUE THREAD

**Issue by ckruse** [wkirschbaum/elixir-ts-mode#20]
Hi there,

it would be nice if an `end` is automatically inserted when a `do` is entered, in a `electric-pair-mode` style. Is this possible?

Best regards,
 CK

**Comment by wkirschbaum** [comment]
Hi. Yes, it is possible. It was actually removed, because it caused some issues with how treesit indentation works. We can leave this open, then I can update once it is done.

**Comment by wkirschbaum** [comment]
I believe this problem can be solved with lsp-server's and/or yasnippets and doubt such a feature would make it in, so closing for now.
