### ISSUE TITLE
unexpected forward-sexp behaviour

### ISSUE THREAD

**Issue by falood** [wkirschbaum/elixir-ts-mode#21]
once I have a line as `{ a } = x`, I expected the cursor go to `}` once it was at `{` and I run `(forward-sexp)` (C-M-f)
but `treesit-end-of-thing` will direct it to the end of the line after `x`
looks like it's not pretty easy to match all kind of brackets `()[]{}<>..` first, maybe provide an option to disable `(setq-local forward-sexp-function #'elixir-ts--forward-sexp)` once elixir-ts-mode enabled?

Thanks

**Comment by wkirschbaum** [comment]
that might make sense. currently it looks at the expression defined in the tree-sitter-elixir grammar. You can tweak elixir-ts-mode by modifying what is seen as an expression by modifying this defconst: 
```
elixir-ts--sexp-regexp
```

We can perhaps make it a defcustom for easier modification? 

Maybe removing binary_operator by default makes sense, but I also don't want to stray too far away from the provided grammar.

**Comment by wkirschbaum** [comment]
@falood do you mind popping this in your init.el after you load elixir-ts-mode? 

```elisp
(defconst elixir-ts--sexp-regexp
  (rx bol
      (or "call" "stab_clause" "list" "tuple" "map" "pair"
          "sigil" "string" "atom" "alias" "arguments" "identifier"
          "boolean" "quoted_content")
      eol))
```

and see how it goes?

**Comment by falood** [comment]
I just gave it a try, the follow config does not work on my end. 

```elisp
(straight-use-package 'elixir-ts-mode)
(defconst elixir-ts--sexp-regexp
  (rx bol
      (or "call" "stab_clause" "list" "tuple" "map" "pair"
          "sigil" "string" "atom" "alias" "arguments" "identifier"
          "boolean" "quoted_content")
      eol))
```

**Comment by wkirschbaum** [comment]
I am not sure how straight-use-package work, but ensure that (defconst elixir-ts--sexp-regexp... gets evaluated after elixir-ts-mode is loaded.  

forward-sexp by default does not incorporate the language, it just cares about generic start/end blocks, hence treesitter having a construct for allowing us to configure the language navigation. If we default to the standard forward-sexp, then we don't get the navigation for actual elixir expressions as we do with ruby and some other languages. 

I am happy for us to tweak what we see as a "navigatable" expression.

**Comment by wkirschbaum** [comment]
@falood i had a look and the elixir-ts-mode is consistent with other -ts-modes. we match on the outer most expression, which is the binary operator, not the tuple. 

This is the grammar output:
```
(binary_operator
 left: (tuple { (identifier) })
 operator: = right: (identifier))
 ```

The tuple is a sub-expression.
