### ISSUE TITLE
Reserved words are not always highlighted

### ISSUE THREAD

**Issue by sirikid** [wkirschbaum/elixir-ts-mode#23]
I accidentally used `end` as the variable name and if it had been highlighted it would've helped a lot.

![elixir-ts-bug](https://user-images.githubusercontent.com/4840430/226183726-218b52bb-22af-43c3-bdfe-bad2a1706a5e.jpg)

**Comment by wkirschbaum** [comment]
We use the follow grammar for deciding what to fontify: https://github.com/elixir-lang/tree-sitter-elixir. Building additional mechanism to override the font is outside the scope of this library. 

One thing we can do however is highlight when there is an error in the parsing of the grammar.

**Comment by sirikid** [comment]
Should I report this to the grammar repo then?

**Comment by wkirschbaum** [comment]
If you use something like eglot, you should get an error like this:
![image](https://user-images.githubusercontent.com/1431483/226197201-13ce8b2b-3038-4e32-a3a3-147b4b79684b.png)

I don't think they should change the grammar for this specific case. 

Let me think about it for a bit and lets keep this open for further comment.

**Comment by sirikid** [comment]
Yeah, you are right. Tbh I am not sure if the lack of highlighting is a bug or a feature.

**Comment by wkirschbaum** [comment]
After looking at this for issue https://github.com/wkirschbaum/elixir-ts-mode/issues/35 it does not make sense to force highlight keywords.
