### ISSUE TITLE
 tree-sitter/:config: No language registered for major mode ‘elixir-ts-mode’

### ISSUE THREAD

**Issue by anildigital** [wkirschbaum/elixir-ts-mode#26]
`⛔ Error (use-package): tree-sitter/:config: No language registered for major mode ‘elixir-ts-mode’`

also see this error when I open .ex file

`File mode specification error: (error No language registered for major mode ‘elixir-ts-mode’)`

Here is my config 
https://github.com/anildigital/emacs/blob/elixir-ts-mode-changes-2/anil/anil-elixir.el
https://github.com/anildigital/emacs/blob/elixir-ts-mode-changes-2/anil/anil-lsp.el

EDIT - This issue can be closed now.

**Comment by wkirschbaum** [comment]
@anildigital have you installed the elixir grammar?

**Comment by anildigital** [comment]
@wkirschbaum yes

**Comment by wkirschbaum** [comment]
Mind posting the versions you are running, tree-sitter and emacs.

**Comment by anildigital** [comment]
Hi
- tree-sitter 0.20.8
- GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.3.0, NS appkit-2299.40 Version 13.2.1 (Build 22D68)) of 2023-02-15

**Comment by wkirschbaum** [comment]
@anildigital you don't need this package in emacs 30, as it is part of emacs now. Maybe update emacs, because prebuilds might not be stable and some things changed.

**Comment by anildigital** [comment]
Package means elixir-ts-mode? Or any other I don't need? Thanks

**Comment by wkirschbaum** [comment]
well, heex-ts-mode and elixir-ts-mode is in emacs core. surface-ts-mode you still need.

**Comment by anildigital** [comment]
@wkirschbaum Thanks. So I don't need elixir-mode (https://github.com/elixir-editors/emacs-elixir)? I still have this with emacs 30 https://github.com/anildigital/emacs/blob/master/anil/anil-elixir.el#L8

**Comment by anildigital** [comment]
@wkirschbaum Upgraded Emacs to `GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.4.0, NS appkit-2299.50 Version 13.3.1 (a) (Build 22E772610a)) of 2023-05-18`  
I am not using the elixir-ts-mode package now as it's part of emacs. 

I have installed grammars via `tree-sitter-langs-install-grammars`

But I still get this error still `⛔ Error (use-package): tree-sitter/:config: No language registered for major mode ‘elixir-ts-mode’`

**Comment by anildigital** [comment]
@wkirschbaum Here is the commit how I upgraded it to use elixir-ts-mode https://github.com/anildigital/emacs/commit/6d216ff9976759bad6d4abd0a03b73bdbeaa7320

**Comment by anildigital** [comment]
@wkirschbaum Error gone after I did this change https://github.com/anildigital/emacs/commit/a1240f78ea4d962e8903140c6f14921e0869c137 😄

**Comment by anildigital** [comment]
@wkirschbaum also here is how my liveview heex code appears. 

<img width="949" alt="image" src="https://github.com/wkirschbaum/elixir-ts-mode/assets/266/a76d8b35-f953-4104-a838-28f3373722b8">

I am not sure if heex-ts-mode is applied or in use.

**Comment by wkirschbaum** [comment]
@anildigital it looks like it is working?

**Comment by anildigital** [comment]
@wkirschbaum Yes, it looks like it's working perfectly. When I ran treesit-explore-mode, it asked me to choose elixir, heex. With Elixir, I could see parse tree and navigate. With heex, I could see parse tree for heex and navigate. 

Thank you for all the great work! 
💚 💙 💜 💛 ❤️
