### ISSUE TITLE
Homebrew process in README slightly incomplete

### ISSUE THREAD

**Issue by walter** [wkirschbaum/elixir-ts-mode#27]
Thanks for all your work on Elixir support in emacs!

I'm just running through the homebrew based process on a new machine and realized that this was missing:

`brew tap d12frosted/emacs-plus`

which is necessary before `brew install emacs-plus@29`.

Might be nice to link back to https://github.com/d12frosted/homebrew-emacs-plus as well.

**Comment by wkirschbaum** [comment]
@walter thanks. Mind making a PR for this?
