### ISSUE TITLE
Add forward-sexp navigation

### ISSUE THREAD

**Issue by wkirschbaum** [wkirschbaum/elixir-ts-mode#3]

**Comment by hochata** [comment]
On Emacs Master, the function `treesit-forward-sexp` was recently added. It seems it only requires to define a `treesit-sexp-type-regexp` local variable per mode.

Several of the builtin modes already support it.

**Comment by wkirschbaum** [comment]
@hochata this package has a minimum requirement of emacs 29 and runs from that branch, so we won't be able to use the function for now, but we can either backport some of the changes or add a condition for a later version of emacs.

**Comment by wkirschbaum** [comment]
basic version added by backporting some code from emacs master. There is an issue where the forward-sexp breaks out, but we can worry about that later.
