### ISSUE TITLE
Improvements for font locking

### ISSUE THREAD

**Issue by scohen** [wkirschbaum/elixir-ts-mode#30]
I was getting elixir-ts-mode set up and noticed what I think are inconsistencies about how font locks are applied, and I'd like to help improve them, if that's what's requested.

I'm looking at [what I think are Emacs's default font locks](https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces-for-Font-Lock.html).

Consider the following snippet:
```elixir
[key: :value]
```
The `key:` has  `font-lock-builtin-face` applied, while `:value` has `font-lock-type-face` applied to it. They're both atoms, so I would expect for them to have the same face. I _sort_ of understand why `:value` has the type face applied, since atoms are modules in erlang, though I would much rather have elixir modules look special and erlang modules look like atoms. It also seems to me that even if we limit ourselves to the default emacs faces, there's probably better faces to choose like `font-lock-constant-face` or `font-lock-property-name-face`.

In the following snippet;
```elixir
  def test() do
```
the parens have `font-lock-keyword-face` despite not being keywords and `font-lock-bracket-face` existing in the emacs defaults.

Is this something that you'd be interested in working on with my help? I know next to nothing about treesitter or elisp.

**Comment by scohen** [comment]
To give you an idea of what the results are:
This is elixir-mode
![Screenshot 2023-10-21 at 12 47 20 PM](https://github.com/wkirschbaum/elixir-ts-mode/assets/55809/40e31520-0246-4e91-9aaf-2ce66d53c913)

and this is elixir-ts-mode
![Screenshot 2023-10-21 at 12 47 44 PM](https://github.com/wkirschbaum/elixir-ts-mode/assets/55809/bdd18963-32d6-47d0-b693-c8b3c99ebaa3)

**Comment by wkirschbaum** [comment]
Closing in favour of https://github.com/wkirschbaum/elixir-ts-mode/issues/35
