### ISSUE TITLE
Variables are font locked as function names

### ISSUE THREAD

**Issue by scohen** [wkirschbaum/elixir-ts-mode#32]
consider the following example:

```elixir
def sum(a, b) do 
  result = a + b
  result
end
```
`a`, `b`, and `result` all receive `font-lock-function-name-face`. 

Instead, i believe the following is correct:
Line 1: `a` and `b` receive `font-lock-variable-name-face`
Line 2: `result` receives `font-lock-variable-name-face`, while `a` and `b` receive `font-lock-variable-use-face`
Line 3: `result` receives `font-lock-variable-use-face`

The above suggestion is admittedly challenging, so having everything be `font-lock-variable-face` is also acceptable.

**Comment by wkirschbaum** [comment]
Closing in favour of https://github.com/wkirschbaum/elixir-ts-mode/issues/35
