### ISSUE TITLE
Function names aren't font-locked with the right rule

### ISSUE THREAD

**Issue by scohen** [wkirschbaum/elixir-ts-mode#33]
First off, please excuse my terminology, it might not be correct, and I'm new to all this, so my debugging might not be 100% right.

I was playing around with trying to get elixir-ts-mode to fontify function definitions differently than function calls. Most things in elixir-ts-mode get treated as function names because of this rule:

```elisp
     (identifier) @font-lock-function-name-face
```
...but most identifiers aren't function names, so I removed the rule.  When I looked at functions with parens, they were still given the `font-lock-function-face-name` face due to this rule (I think):
```elisp
(call
      target: (identifier) @font-lock-keyword-face
      (:match ,elixir-ts--definition-keywords-re @font-lock-keyword-face))
     (call
```

But those without parens were not, and were given `font-lock-variable-name-face` despite no rule specifying it.

**Comment by wkirschbaum** [comment]
Closing in favour of https://github.com/wkirschbaum/elixir-ts-mode/issues/35
