### ISSUE TITLE
incorrect parsing when keywords included inside docstrings

### ISSUE THREAD

**Issue by thebinary** [wkirschbaum/elixir-ts-mode#46]
I am not certain if this is an issue related to this particular `ts-mode` or `smartparens-mode` or `elixir-treesitter` itself. But it seems like *keywords inside docstrings* are being parsed as *keywords* instead of simply taken as strings.

With `smartparens-mode` active, the issue is visually reflected as some example screenshots given below:

### Correct parsing
Here, the `defmodule` begin and end is correctly parsed.
<img width="877" alt="Screenshot 2024-04-19 at 13 16 51" src="https://github.com/wkirschbaum/elixir-ts-mode/assets/14862656/cebfc60e-d444-4175-b545-c6b176f0cf71">

### Incorrent parsings due to keywords inside docstring
Here, the `defmodule` begin and end is **MISLEAD** by `for` string inside the `moduledoc`
<img width="929" alt="Screenshot 2024-04-19 at 13 07 54" src="https://github.com/wkirschbaum/elixir-ts-mode/assets/14862656/d9649a02-d2fd-4b41-8132-99946f70c604">

Here, the `for` inside docstring is shown to have no end because of `defmodule` string ahead of it inside the `moduledoc`.
<img width="1136" alt="Screenshot 2024-04-19 at 13 08 33" src="https://github.com/wkirschbaum/elixir-ts-mode/assets/14862656/3197be21-aa62-470e-aa52-31e7a9e637d3">

**Comment by thebinary** [comment]
Apologies, seems like issue with `smartparens-mode`. Since `treesit-beginning-of-defun` and `treesit-end-of-defun` functions are working **correctly**.

**Comment by wkirschbaum** [comment]
@thebinary there was a discussion about this on emacs-devel and think there are ways to make it work better together, but it won't happen soon.
