### ISSUE TITLE
No syntax highlighting on Elixir files

### ISSUE THREAD

**Issue by 1player** [wkirschbaum/elixir-ts-mode#5]
I've just tried this package on a freshly-compiled version of Emacs master, and I lost syntax highlight on .ex and .exs files. Heex files work fine.

The elixir tree-sitter grammar has been installed with the system package manager from git, heex from source with `treesit-install-language-grammar`. When I open an Elixir file I get this in the Warnings buffer:

```
Error during redisplay: (jit-lock-function 1) signaled (treesit-query-error "Node type error at" 9 "(sigil (sigil_name) @name (#match \"^[H]$\" @name) (quoted_content) @heex)" "Debug the query with `treesit-query-validate'")
```

**Comment by 1player** [comment]
Nevermind, the Elixir grammar was incompatible. If anyone else has the same issue, do not use https://aur.archlinux.org/packages/tree-sitter-elixir-git but compile the official grammar yourself from https://github.com/elixir-lang/tree-sitter-elixir

**Comment by wkirschbaum** [comment]
Thanks for logging the issue. We should probably update the aur package as more people will run into this, or at least update the readme/docs. Lets keep this open for now.

**Comment by wkirschbaum** [comment]
This should give a clear message when the language version is too old: https://github.com/wkirschbaum/elixir-ts-mode/commit/c9aef25863433f14f569afaa0cb907b269a1e79d
