### ISSUE TITLE
Publish to (NonGnu) Elpa?

### ISSUE THREAD

**Issue by hochata** [wkirschbaum/elixir-ts-mode#6]
Hi!

Thanks for the packages. I've been using them from the Git repo and really like them. I see the package was recently added to Melpa.

Are there any plans of adding them to either [NonGnu Elpa](https://elpa.nongnu.org/) or [Elpa](https://elpa.gnu.org/)?

The advantage would be that both of those repositories come enabled by default in Emacs 28 and later.

**Comment by wkirschbaum** [comment]
@hochata thank you, happy that you find it useful. I am hoping to get it into emacs core, but waiting for some paperwork. My experience around melpa/elpa etc.. is very limited so just stuck with how elixir-mode is currently released do that we can potentially add {elixir,heex}-ts-mode as a dependency to the current elixir-mode if people so desire.

If you have any suggestions on how this might work it will be very welcome.

**Comment by hochata** [comment]
I haven't thought about integrating it with the already existing Elixir mode. And while it is possible to have the package in several different Emacs package repositories, I agree the best way would be to have this package on Melpa for the moment.

Of course, having it builtin would be way better :smiley_cat: .

I'm looking forward to seeing this in Emacs 30!
