### ISSUE TITLE
What's the best way to reformat an Elixir buffer?

### ISSUE THREAD

**Issue by 1player** [wkirschbaum/elixir-ts-mode#9]
I used to have a before-save hook with elixir-mode that reformatted the file upon save. Since this package is incompatible with elixir-mode, which is the best way of formatting a buffer?

I imagine I would have to install elixir-mode, configure it so elixir-ts-mode is used for font-lock, but use elixir-mode's formatting command, is that correct?

**Comment by wkirschbaum** [comment]
I believe you can use `indent-region` which is usually bound to `C-M-\`. If you use eglot you can use eglot-format and if you use lsp-mode, there is also a format command. Formatting the whole buffer is probably better to use either eglot or lsp-mode's format command as the indentation from elixir-ts-mode will not be the same as the mix formatter. 

Would one of the above options work? 

There are two ways we can move forward:
1) try to make elixir-ts-mode's indentation work 100% the same as mix format ( which might make is slower )
2) try to add something similar to what elixir-mode has ( i never used it, so not sure if it worked well enough )

**Comment by 1player** [comment]
Thanks, I was indeed having issues with elixir-mode format on save (it creates temporary files in the project dir which tend to be picked up by live reload and cause issues)

Since I use eglot, I fixed by reinstalling this package and adding:

```
; Truncated for brevity
(use-package eglot
  :init
  ; From https://go.googlesource.com/tools/+/refs/heads/master/gopls/doc/emacs.md
  (defun eglot-format-buffer-on-save ()
    (add-hook 'before-save-hook #'eglot-format-buffer -10 t)))

(use-package elixir-ts-mode
  :config
  (add-hook 'elixir-ts-mode-hook #'eglot-format-buffer-on-save))
```

which seems to work great. 

I would expect the LSP client to handle all the intricacies of mix format, so this package can be kept slim by simply delegating it to eglot.
